@startuml C4_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title Skill Monolito

Person(usuario, "Usuario", "Gestiona su biblioteca por voz")
System_Ext(alexa, "Amazon Alexa", "Convierte voz ↔ intents/slots")
System(skill, "Skill Biblioteca Personal", "Modelo de interacción (intents, slots)")
System(backend, "AWS Lambda (Backend)", "Handlers y lógica de la skill")
SystemDb(s3, "Amazon S3", "Guarda/lee la biblioteca del usuario (JSON)")

Rel(usuario, alexa, "Habla comandos", "Voz")
Rel(alexa, skill, "Intents/Slots", "Request/Response")
Rel(skill, backend, "Invoca Lambda", "Request/Response")
Rel(backend, s3, "Guardar / Leer datos", "Operaciones de datos")
Rel(alexa, usuario, "Respuestas habladas", "Audio")
@enduml
